memory_trunk/memory_trunk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from memory_trunk_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('memory_trunk_app.urls'), name='memory_trunk_app')
]

memory_trunk/memory_trunk_app/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.decorators import login_required

app_name = 'memory_trunk_app'
urlpatterns = [

    # LANDING PAGE

    url(r'^$', views.IndexView.as_view(), name='index'),


    # AUTHENTICATION
    
    url(r'^register_user', views.register_user, name='register_user'),
    url(r'^user_registration', views.UserRegistration.as_view(), name='user_registration'),
    url(r'^login_user', views.login_views.login_user, name='login_user'),
    url(r'^logout_user', views.login_views.logout_user, name='logout_user'),
    url(r'^login', views.login_views.LoginUserView.as_view(), name='login_user_view'),


    # CREATION FORMS
    
        # Memory
    url(r'^hippocampus', views.hippocampus_view, name='hippocampus'),
    
        # Tip
    url(r'^tip_creation', views.tip_creation_view, name='tip_creation'),

        # Perspective
    url(r'^perspective_creation', views.perspective_creation_view, name='perspective_creation'),


    # LIST VIEWS

        # Memory
    url(r'^memory_list/(?P<id>\d+)/$', login_required(views.MemoryListView.as_view()), name='memory_list'),
    url(r'^community_memories/', views.PublicMemoryListView.as_view(), name='public_memory_list'),
    url(r'^liked_memories/(?P<id>\d+)/$', views.LikedMemoriesView.as_view(), name='liked_memories'),

        # Tip
    url(r'^tip_list/(?P<id>\d+)/$', login_required(views.TipListView.as_view()), name='tip_list'),
    url(r'^community_tips/', views.PublicTipListView.as_view(), name='public_tip_list'),
    url(r'^liked_tips/(?P<id>\d+)/$', views.LikedTipsView.as_view(), name='liked_tips'),

        # Perspective
    url(r'^perspective_list/(?P<id>\d+)/$', login_required(views.PerspectiveListView.as_view()), name='perspective_list'),
    url(r'^community_perspectives/', views.PublicPerspectiveListView.as_view(), name='public_perspective_list'),
    url(r'^liked_perspectives/(?P<id>\d+)/$', views.LikedPerspectivesView.as_view(), name='liked_perspectives'),


    # DETAIL VIEWS
    
        # Memory
    url(r'^memory_detail/(?P<id>\d+)/$', views.MemoryDetailView.as_view(), name='memory_detail'),
    
        # Tip
    url(r'^tip_detail/(?P<id>\d+)/$', views.TipDetailView.as_view(), name='tip_detail'),
    
        # Perspective
    url(r'^perspective_detail/(?P<id>\d+)/$', views.PerspectiveDetailView.as_view(), name='perspective_detail'),


    # OBJECT DELETION VIEWS

        # Memory
    url(r'^delete_memory/(?P<id>\d+)/$', views.delete_memory, name='delete_memory'),
    
        # Tip
    url(r'^delete_tip/(?P<id>\d+)/$', views.delete_tip, name='delete_tip'),
    
        # Perspective
    url(r'^delete_perspective/(?P<id>\d+)/$', views.delete_perspective, name='delete_perspective'),


    # OBJECT UPDATE VIEWS

        # Memory
    url(r'^update_memory/(?P<id>\d+)/$', views.update_memory, name='update_memory'),

        # Tip
    url(r'^update_tip/(?P<id>\d+)/$', views.update_tip, name='update_tip'),

        # Perspective
    url(r'^update_perspective/(?P<id>\d+)/$', views.update_perspective, name='update_perspective'),


    # LIKES AND FOLLOWS PROCESSING

        # Memory
    url(r'^like_memory/(?P<id>\d+)/$', views.like_memory, name='like_memory'),
    url(r'^dislike_memory/(?P<id>\d+)/$', views.dislike_memory, name='dislike_memory'),

        # Tip
    url(r'^like_tip/(?P<id>\d+)/$', views.like_tip, name='like_tip'),
    url(r'^dislike_tip/(?P<id>\d+)/$', views.dislike_tip, name='dislike_tip'),

        # Memory
    url(r'^like_perspective/(?P<id>\d+)/$', views.like_perspective, name='like_perspective'),
    url(r'^dislike_perspective/(?P<id>\d+)/$', views.dislike_perspective, name='dislike_perspective'),


    # SEARCH
    url(r'^search/$', views.search, name='search'),


    # HAPPY

        # Memory
    url(r'^happy_memory/$', views.happy_memory, name='happy_memory'),






] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

memory_trunk/memory_trunk_app/forms/memory_form.py
from django.forms import ModelForm, Textarea
from memory_trunk_app import models
from django.utils.translation import ugettext_lazy as _
from datetimewidget.widgets import DateTimeWidget


class MemoryForm(ModelForm):
    """
    Purpose:
        Instantiate forms to create Memory objects

    Author: Sam Phillips <samcphillips.com>
    """

    class Meta:
        model = models.Memory
        fields = ['title', 'is_public', 'date', 'location', 'content', 'happy_factor', 'sad_factor', 'tags',]
        labels = {
            'is_public': _('Share this Memory with other users?'),
            'date': _('Date (yyyy-mm-dd)'),
            'happy_factor': _('How happy does this memory make you? (0-10)'),
            'sad_factor': _('How sad does this memory make you? (0-10)'),
        }
        widgets = {
            'content': Textarea(attrs={'id': 'object_content'}),
        }

memory_trunk/memory_trunk_app/views/delete_memory_view.py
from memory_trunk_app import models
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse

def delete_memory(request, id):
    """
    Purpose:
        Processes the deletion of a Memory instance and redirects the user 
        to their Memory list

    Arguments:
        id -- The primary key of the Memory instance to be deleted

    Author: Sam Phillips <samcphillips.com>
    """

    memory = models.Memory.objects.get(id=id)
    if memory.user.id == request.user.id:
        memory.delete()    
    return HttpResponseRedirect(reverse('memory_trunk_app:memory_list', args=(request.user.id,)))

memory_trunk/memory_trunk_app/views/delete_perspective_view.py
from memory_trunk_app import models
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse

def delete_perspective(request, id):
    """
    Purpose:
        Processes the deletion of a Perspective instance and redirects 
        the user to their Perspective list

    Arguments:
        id -- The primary key of the Perspective instance to be deleted

    Author: Sam Phillips <samcphillips.com>
    """

    perspective = models.Perspective.objects.get(id=id)
    if perspective.user.id == request.user.id:
        perspective.delete()
    return HttpResponseRedirect(reverse('memory_trunk_app:perspective_list', args=(request.user.id,)))

memory_trunk/memory_trunk_app/views/delete_tip_view.py
from memory_trunk_app import models
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse

def delete_tip(request, id):
    """
    Purpose:
        Processes the deletion of a Tip instance and redirects 
        the user to their Tip list

    Arguments:
        id -- The primary key of the Tip instance to be deleted

    Author: Sam Phillips <samcphillips.com>
    """

    tip = models.Tip.objects.get(id=id)
    if tip.user.id == request.user.id:
        tip.delete()    
    return HttpResponseRedirect(reverse('memory_trunk_app:tip_list', args=(request.user.id,)))

memory_trunk/memory_trunk_app/views/happy_memory.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from memory_trunk_app import models
import random

def happy_memory(request):
    """
    Purpose:
        Grab a random happy Memory from the active user's Memory list 
        and render it in a Memory detail view. If user has no happy 
        Memories, we must give them a hug. After we give them a hug 
        (and perhaps some hot cocoa) we grab a random happy Memory 
        from the list of publicly available memories

    Author: Sam Phillips <samcphillips.com>
    """

    memories = None
    index = None
    mem_instance = request.GET.get('mem_instance', 0)

    try:
        memories = models.Memory.objects.filter(user=request.user, happy_factor__gte=6).exclude(id=mem_instance)
        index = random.randrange(0, len(memories))
    except (ValueError, TypeError) as e:
        memories = models.Memory.objects.filter(happy_factor__gte=6, is_public=True).exclude(id=mem_instance)
        index = random.randrange(0, len(memories))
    happy_memory = memories[index]
    print(happy_memory)
    return HttpResponseRedirect(reverse(
        'memory_trunk_app:memory_detail', 
        kwargs={'id':happy_memory.id}
    ))

memory_trunk/memory_trunk_app/views/hippocampus_view.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse
from memory_trunk_app.forms import MemoryForm
from memory_trunk_app import models

@login_required
def hippocampus_view(request):
    """
    Purpose:
        Provide a user interface for creating Memory Objects

    Author: Sam Phillips <samcphillips.com>
    """

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = MemoryForm(request.POST)
        if form.is_valid():
            memory = models.Memory.objects.create(
                user=request.user,
                title=form.cleaned_data['title'],
                is_public=form.cleaned_data['is_public'],
                date=form.cleaned_data['date'],
                location=form.cleaned_data['location'],
                content=form.cleaned_data['content'],
                happy_factor=form.cleaned_data['happy_factor'],
                sad_factor=form.cleaned_data['sad_factor']
            )
            for tag in form.cleaned_data['tags']:
                memory.tags.add(tag)
            memory.save()

            return HttpResponseRedirect(reverse('memory_trunk_app:memory_detail', args=(memory.id,)))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = MemoryForm()

    return render(
        request, 
        'hippocampus.html', 
        {
            'form': form,
            'page_title': 'Make a Memory'
        }
    )

memory_trunk/memory_trunk_app/views/index_view.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
from memory_trunk_app import models

class IndexView(TemplateView):
    """
    Purpose:
        This view serves as the landing page for MemoryTrunk

    Author: Sam Phillips <samcphillips.com>
    """

    template_name = "index.html"
    context = {}

    def get(self, request):
        """
        Retrieves the last ten instances created of each model for 
        displaying their links on the index view
        """
        self.context['memories'] = models.Memory.objects.filter(is_public=True).order_by('-id')[:10][::-1]
        self.context['tips'] = models.Tip.objects.filter(is_public=True).order_by('-id')[:10][::-1]
        self.context['perspectives'] = models.Perspective.objects.filter(is_public=True).order_by('-id')[:10][::-1]
        return render(request, self.template_name, self.context)

memory_trunk/memory_trunk_app/views/liked_memories_view.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
from django.contrib.auth.models import User
from memory_trunk_app import models

class LikedMemoriesView(TemplateView):
    """
    Purpose: 
        List all of the Memories a user has liked as hyperlinked titles
    
    Author: Sam Phillips <samcphillips.com>
    """
    template_name = 'memory_list.html'

    def get(self, request, id):
        memories = request.user.memory_likes.all()
        return render(
            request, 
            self.template_name, 
            {
                'memories': memories,
                'page_title': 'Liked Memories'
            }
        )

memory_trunk/memory_trunk_app/views/liked_perspectives_view.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
from django.contrib.auth.models import User
from memory_trunk_app import models

class LikedPerspectivesView(TemplateView):
    """
    Purpose: 
        List all of the Perspectives a user has liked as hyperlinked titles
    
    Author: Sam Phillips <samcphillips.com>
    """
    template_name = 'perspective_list.html'

    def get(self, request, id):
        perspectives = request.user.perspective_likes.all()
        return render(
            request, 
            self.template_name, 
            {
                'perspectives': perspectives,
                'page_title': 'Liked Perspectives'
            }
        )

memory_trunk/memory_trunk_app/views/liked_tips_view.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
from django.contrib.auth.models import User
from memory_trunk_app import models

class LikedTipsView(TemplateView):
    """
    Purpose: 
        List all of the Tips a user has liked as hyperlinked titles
    
    Author: Sam Phillips <samcphillips.com>
    """
    template_name = 'tip_list.html'

    def get(self, request, id):
        tips = request.user.tip_likes.all()
        return render(
            request, 
            self.template_name, 
            {
                'tips': tips,
                'page_title': 'Liked Tips'
            }
        )

memory_trunk/memory_trunk_app/views/login_user.py
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect


def login_user(request):
    """
    Purpose: 
        Login a user using their username and password
    
    Author: Sam Phillips <samcphillips.com>
    """
    data = request.POST

    username = data['username']
    password = data['password']

    user = authenticate(username=username, password=password)

    if user is not None:
        login(request=request, user=user)
    else:
        # Not successful, redirect to index page
        return HttpResponseRedirect(redirect_to='/')
    # Successful, redirect to index page
    return HttpResponseRedirect(redirect_to='/')

# def logout_view(request):
#     logout(request)
#     return HttpResponseRedirect(redirect_to='/')

memory_trunk/memory_trunk_app/views/login_views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect

class LoginUserView(TemplateView):
    """
    Purpose:
        Provide users with a form for logging in

    Author: Sam Phillips <samcphillips.com>
    """
    template_name = "login_user.html"

def login_user(request):
    """
    Purpose: 
        Login a user using their username and password
    
    Author: Sam Phillips <samcphillips.com>
    """
    data = request.POST

    username = data['username']
    password = data['password']

    user = authenticate(username=username, password=password)

    if user is not None:
        login(request=request, user=user)
    else:
        # Not successful, redirect to index page
        return HttpResponseRedirect(redirect_to='/')
    # Successful, redirect to index page
    return HttpResponseRedirect(redirect_to='/')

def logout_user(request):
    """
    Purpose:
        Logout the user requesting this view

    Author: Sam Phillips <samcphillips.com>
    """
    logout(request)
    return HttpResponseRedirect(redirect_to='/')

memory_trunk/memory_trunk_app/views/memory_detail_view.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from memory_trunk_app import models
from django.urls import reverse

class MemoryDetailView(TemplateView):
    """
    Purpose: 
        Display the detaiils of a specific Memory object
    
    Author: Sam Phillips <samcphillips.com>
    """
    template_name = 'memory_detail.html'

    def get(self, request, id):
        memory = models.Memory.objects.get(id=id)
        if memory.is_public == False:
            if memory.user != request.user:
                return HttpResponseRedirect(redirect_to='/')
        return render(request, self.template_name, {'memory': memory})

def like_memory(request, id):
    """
    Purpose:
        Provide a means for users to 'like' a memory, thus allowing 
        them to view it at a later date

    Arguments:
        id -- The primary key of the Memory object to be liked by 
        the user

    Author: Sam Phillips <samcphillips.com>
    """
    if request.user.is_anonymous():
        return HttpResponseRedirect(reverse('memory_trunk_app:user_registration'))
    memory = models.Memory.objects.get(id=id)
    memory.likes.add(request.user)
    return HttpResponseRedirect(reverse('memory_trunk_app:memory_detail', args=(memory.id,)))


def dislike_memory(request, id):
    """
    Purpose:
        Provide a means for users to 'unlike' a Memory, thus removing 
        it from their saved memories

    Arguments:
        id -- The primary key of the Memory object to be unliked by 
        the user

    Author: Sam Phillips <samcphillips.com>
    """
    memory = models.Memory.objects.get(id=id)
    memory.likes.remove(request.user)
    return HttpResponseRedirect(reverse('memory_trunk_app:memory_detail', args=(memory.id,)))

memory_trunk/memory_trunk_app/templates/hippocampus.html
{% extends 'index.html' %}
{% block content %}
    <div class="row">
        <form class="object-maker col-md-6 col-md-offset-3 content-block" action="{% url 'memory_trunk_app:hippocampus' %}" method="post">
            <h1>{{page_title}}</h1>
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-success" type="submit">Save Memory</button>
        </form>
    </div>
{% endblock %}

memory_trunk/memory_trunk_app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>MemoryTrunk</title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'lib/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>

{# navbar start #}
    <nav class="navbar navbar-default">
    {# <nav class="navbar navbar-default navbar-fixed-top"> #}
        <div class="container-fluid navvy bordered">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">MemoryTrunk</a>
            </div>

            {# navbar for authenticated users #}
            {% if user.is_authenticated %}
            
                <!-- Menu Left Justified -->
                <ul class="nav navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Community <span class="glyphicon glyphicon-triangle-bottom"></span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'memory_trunk_app:public_memory_list' %}
                            ">Memories</a>
                            <a class="dropdown-item" href="{% url 'memory_trunk_app:public_tip_list' %}
                            ">Tips</a>
                            <a class="dropdown-item" href="{% url 'memory_trunk_app:public_perspective_list' %}
                            ">Perspectives</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            My Trunk <span class="glyphicon glyphicon-triangle-bottom"></span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/memory_list/{{request.user.id}}">Memories</a>
                            <a class="dropdown-item" href="/tip_list/{{request.user.id}}">Tips</a>
                            <a class="dropdown-item" href="/perspective_list/{{request.user.id}}">Perspectives</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Likes <span class="glyphicon glyphicon-triangle-bottom"></span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/liked_memories/{{request.user.id}}">Memories</a>
                            <a class="dropdown-item" href="/liked_tips/{{request.user.id}}">Tips</a>
                            <a class="dropdown-item" href="/liked_perspectives/{{request.user.id}}">Perspectives</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Create <span class="glyphicon glyphicon-triangle-bottom"></span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="/hippocampus">New Memory</a>
                            <a class="dropdown-item" href="/tip_creation">New Tip</a>
                            <a class="dropdown-item" href="/perspective_creation">New Perspective</a>
                        </div>
                    </li>
                </ul>

                <!-- Menu Right Justified -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form action="{% url 'memory_trunk_app:happy_memory' %}">
                                <button id="happy-button" class="btn shadowed" type='submit'>
                                    {% if memory%}
                                        <input type="hidden" name="mem_instance" value="{{memory.id}}">
                                    {% endif %}
                                    Happy Memory <span class="glyphicon glyphicon-heart-empty"></span>
                                </button>
                            </form>
                        </li>
                        <li><a href="#">Welcome, {{ user.first_name }} {{ user.last_name }}</a></li>
                        <li><a href="{% url 'memory_trunk_app:logout_user' %}">Logout</a></li>
                    </ul>
                </div>

            {# navbar for unauthenticated users #}
            {% else %}
              <!-- Menu Left Justified -->
                <ul class="nav navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Community Trunk <span class="glyphicon glyphicon-menu-down"></span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'memory_trunk_app:public_memory_list' %}
                            ">Memories</a>
                            <a class="dropdown-item" href="{% url 'memory_trunk_app:public_tip_list' %}
                            ">Tips</a>
                            <a class="dropdown-item" href="{% url 'memory_trunk_app:public_perspective_list' %}
                            ">Perspectives</a>
                        </div>
                    </li>
                </ul>

              <!-- Menu Right Justified -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form action="{% url 'memory_trunk_app:happy_memory' %}">
                                <button id="happy-button" class="btn shadowed" type='submit'>
                                    {% if memory%}
                                        <input type="hidden" name="mem_instance" value="{{memory.id}}">
                                    {% endif %}
                                    Happy Memory <span class="glyphicon glyphicon-heart-empty"></span>
                                </button>
                            </form>
                        </li>
                        <li><a href="{% url 'memory_trunk_app:login_user_view' %}">Login</a></li>
                        <li><a href="{% url 'memory_trunk_app:user_registration' %}">Register</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            {% endif %}
        </div><!-- /.container-fluid -->
    </nav>
{# navbar end #}
    <div class="container-fluid mt-header">
        <div class="row">
            <div class="col-md-12 container">
                <div class="row">
                    <div class="col-sm-6">
                        <h1 class="positive-title">MemoryTrunk</h1>
                        <p class="positive-title">  &nbsp;  &nbsp; Crowdsourcing Life Experiences</p>
                    </div>
                    {# search bar #}
                    <form class="col-sm-5 search-form container-fluid" action="{% url 'memory_trunk_app:search' %}" method="get">
                        <div class="row">
                            <input type="text" class="col-md-10 search-input" placeholder="Search" name="query">
                            <button class="btn btn-default glyphicon glyphicon-search col-md-2 search-input" type="submit">
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div id="index_content_holder" class="container-fluid">
        {% block content %}
            {# Header #}

            {# Body containing blocks for last ten Memory, Tip, and Perspective objects #}
            <div class="row">
                <div class="col-sm-10 col-sm-offset-1 container-fluid">
                    <div id="index_community_blocks" class="row">
                        <div class="content-block index-block col-sm-4">
                            
                                <h2 class="content-title"><a href="{% url 'memory_trunk_app:public_memory_list' %}">Memories</a></h2>
                            
                            {% for mem in memories %}
                                <div class="listed-object">
                                    <a href="{% url 'memory_trunk_app:memory_detail' id=mem.id %}">
                                        <h3 class="object-title">{{mem.title}}</h3>
                                    </a>
                                    <h5>by {{mem.user.username}}</h5>
                                    <span class="glyphicon glyphicon-thumbs-up"></span>
                                    ({{mem.get_likes_count}})
                                </div>
                            {% endfor %}
                        </div>
                        <div class="content-block index-block col-sm-4">
                            <h2 class="content-title"><a href="{% url 'memory_trunk_app:public_tip_list' %}">Tips</a></h2>
                            {% for tip in tips %}
                                <div class="listed-object">
                                    <a href="{% url 'memory_trunk_app:tip_detail' id=tip.id %}">
                                        <h3 class="object-title">{{tip.title}}</h3>
                                    </a>
                                    <h5>by {{tip.user.username}}</h5>
                                    <span class="glyphicon glyphicon-thumbs-up"></span>
                                    ({{tip.get_likes_count}})
                                </div>
                            {% endfor %}
                        </div>
                        <div class="content-block index-block col-sm-4 last_cb">
                            <h2 class="content-title"><a href="{% url 'memory_trunk_app:public_perspective_list' %}">Perspectives</a></h2>
                            {% for perspective in perspectives %}
                                <div class="listed-object">
                                    <a href="{% url 'memory_trunk_app:perspective_detail' id=perspective.id %}">
                                        <h3 class="object-title">{{perspective.title}}</h3>
                                    </a>
                                    <h5>by {{perspective.user.username}}</h5>
                                    <span class="glyphicon glyphicon-thumbs-up"></span>
                                    ({{perspective.get_likes_count}})
                                </div>
                            {% endfor %}
                        </div>
                        
                    </div>
                    
                </div>
            </div>
        {% endblock %}
    </div>

    <div class="footer">
        <a href="https://samcphillips.com"><h6>&copy; Sam Phillips 2017</h6></a>
    </div>

<script src="{% static 'lib/jquery.min.js' %}"></script>
<script src="{% static 'lib/bootstrap.min.js' %}"></script>
</body>
</html>

memory_trunk/memory_trunk_app/templates/memory_update_form.html
{% extends 'index.html' %}

{% block content %}
    <div class="row">
        <form class="object-maker col-md-6 col-md-offset-3 content-block" action="{% url 'memory_trunk_app:update_memory' id=memory.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Update" />
        </form>
    </div>
{% endblock %}

memory_trunk/memory_trunk_app/templates/perspective_creation.html
{% extends 'index.html' %}
{% block content %}
    <div class="row">
        <form class="object-maker col-sm-6 col-sm-offset-3 content-block" action="{% url 'memory_trunk_app:perspective_creation' %}" method="post">
            <h1>{{page_title}}</h1>
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-success" type="submit">Save Perspective</button>
        </form>
    </div>
{% endblock %}